#!/bin/sh

echo -n "Ensuring clean folder... " && cd .. && make -s fclean && wait && echo "Done."
echo -n "Making all... " && make -s all && wait && cd tests && echo "Done."
echo -n "Compiling all..." && cc -s -Wall -Werror -Wextra -I.. -o test main.c ../libftprintf.a ../libft/libft.a && wait && echo "Done."
valgrind ./test && wait
echo -n "Cleaning folder... " && cd .. && make -s fclean && wait && cd tests && rm -f test && wait && echo "Done."
echo "Completed."
